# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginDatetime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=16, verbose_name='User name')),
                ('user_login_datetime', models.DateTimeField(verbose_name='User login datetime')),
            ],
        ),
    ]
