# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginDatetime',
        ),
    ]
