# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 21:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.CharField(max_length=300, verbose_name='Text answer')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300, verbose_name='Question text')),
                ('question_update', models.DateTimeField(verbose_name='Survey last update datetime')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=100, verbose_name='Option text')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollsApp.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='Question number in the survey')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollsApp.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(max_length=100, verbose_name='Survey name')),
                ('survey_description', models.CharField(blank=True, max_length=1000, verbose_name='Survey description')),
                ('survey_update', models.DateTimeField(verbose_name='Survey last update datetime')),
            ],
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_update', models.DateTimeField(verbose_name='User survey response update datetime')),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollsApp.Survey')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionorder',
            name='survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollsApp.Survey'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollsApp.QuestionOptions'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollsApp.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='user_survey_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PollsApp.UserSurvey'),
        ),
    ]
